services:
  api:
    build: .
    restart: always
    container_name: costeador_api_service
    
    # --- ACCESO DIRECTO ---
    # Esto abre el puerto 8000 para que entres con tu IP
    ports:
      - "8000:8000"
    
    volumes:
      - ./app:/code/app
    environment:
      - TZ=America/Mexico_City

    # Usamos la red por defecto de Docker
    networks:
      - default
